### ISSUE TITLE
Make it clear what timestamp the minEnactment network params reference

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/documentation#230]
https://docs.vega.xyz/docs/mainnet/concepts/vega-protocol#thresholds-for-network-parameters

Tell us about network parameters for min enactment. It would be handy in this context to make it clear that this is the duration after the vote closes on a proposal (I was in doubt about whether it was after the proposal was first opened).

the [spec](https://github.com/vegaprotocol/specs/blob/master/protocol/0028-GOVE-governance.md) had an answer for me.

**Comment by neildawson** [comment]
Candida mentioned this to me since I wrote [something similar](https://docs.vega.xyz/docs/testnet/tutorials/proposals/new-market-proposal#voting-and-enactment) for governance tutorials, so I had a go at adding some more detail in the concepts section, too.

[Deploy preview](https://deploy-preview-274--vega-docusaurus.netlify.app/docs/testnet/concepts/vega-protocol#thresholds-for-network-parameters)

Changes:

- reordered the parameters so they come in an order compatible with the story of submitting a proposal
- rewrote the example so it reads as a story explains the meaning of each parameter
- added a heading to make the example more explicit

I tried making a table with the generic parameter names alongside the example and story, but it felt more complicated so went with this instead.
