### ISSUE TITLE
Add high-level wallet concepts

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/documentation#30]
Closes #50 
Create a page that 
- [x] explains high-level concepts about the wallet
- [ ] includes diagrams for those descriptions

**Comment by campbellssource** [comment]
Working on diagrams here: https://www.figma.com/file/srdGfoI55a58VBnGPpaTYV/Vega-Explainers?node-id=426%3A99
Will post update here when I think I'm close.

**Comment by ValentinTrinque** [comment]
**On the naming:**
- `backup phrase` -> `recovery phrase` : that's what we selected
- `username` -> `name` : there is no such thing as username, it can even be misleading because username usually imply uniqueness and one-per-person. Here we can have multiple wallet, so... it doesn't really map onto one another.
- `password` -> `passphrase`: "each with their own password" and right after "unless they know the passphrase"
- `thier` -> `their`: small typo

The next part is subjective.

**On explanation:**
- `Each new key pair is generated using the same recovery phrase` : Not sure what we are supposed to understand here. Is it the "deterministic" part of the generation (always get the same keys in the same order), or the "derivation" part (it's attached to your recovery phrase), or both ?
- `User of wallet 1 can not see or use wallet 2 (unless they know the passphrase)`: it feels like we are biased by the hosted wallet here, which doesn't feel right, especially on the concept of "user account". Sure, you can do "user accounts", but you could also just have one user with multiple wallet. And I think we are more inclined to have the latter. To me, talking about "user accounts" makes things more complicated that it is. Is there anything preventing us to just resume this to "You can have multiple wallets. And, each wallet can have its own passphrase." ?

**On the design:**
- I like the minimalism of the diagram. It helps to focus on the content.
- `A dApp needs to know the location of a wallet`: since the begin, I am a bit uncomfortable with the term `location`, because it also implies "file location", whereas we know it's the service URL. And, for the record, we troubleshooted users that were pasting the file location in the frontend. So I think we should change this term and introduce the notion of the "service". At some point, they will have to deal with it on our front-ends, so we have to introduce this so they are not lost while "practicing". Something like, "To access your wallet, a dApp will have to go through a service. As a result, we need to tell the dApp what's the service URL". Then we can emphasise on "This service allows dApps to manage your keys and sign transactions on your behalf".
- Mixing the "login" and "send transaction" makes it hard to understand the flow on the arrows. And that would be magnified if we introduce the notion of service, and the network configuration (not yet explained). What about splitting the diagram in 2 ? On one side, `dApp <-> Service <-> Wallets` and on the other side, we can have a dedicated diagram, where we could use all the space to explain the flow with key and network selection, signing, and sending of the tx. That should help to highlight the transaction payload going from the "raw", to the "signed", and then "sent" state.

What do you think ?

**Comment by campbellssource** [comment]
Here is another iteration. Here the diagrams are broken up a little more...
I've placed these within the some draft text in [Figma](https://www.figma.com/file/srdGfoI55a58VBnGPpaTYV/Vega-Explainers?node-id=426%3A99). 
<img width="1694" alt="Screenshot 2022-02-08 at 12 31 13" src="https://user-images.githubusercontent.com/13255539/152987504-7c1177b3-4d3c-4475-a7fb-e14dc4caa720.png">
<img width="1727" alt="Screenshot 2022-02-08 at 12 32 11" src="https://user-images.githubusercontent.com/13255539/152987679-37f69cd1-4424-4fbe-be4e-047469a3cb94.png">
<img width="1707" alt="Screenshot 2022-02-08 at 12 33 03" src="https://user-images.githubusercontent.com/13255539/152987810-80f9f6f2-4aeb-44d8-93b4-1b85cfc5cb5b.png">
<img width="1439" alt="Screenshot 2022-02-08 at 12 33 16" src="https://user-images.githubusercontent.com/13255539/152987858-b045ba9a-b068-422a-b977-703a790aa2f7.png">
<img width="1420" alt="Screenshot 2022-02-08 at 12 33 32" src="https://user-images.githubusercontent.com/13255539/152987898-1904560e-6a1d-4a93-bd38-52f4020a2a90.png">
Still pretty rough.

- - - - - - - 

And here is everything in 2 diagrams again.
<img width="1307" alt="Screenshot 2022-02-08 at 12 37 45" src="https://user-images.githubusercontent.com/13255539/152988601-bcecb442-a27f-4f5f-b3dc-dabdbdbbb2f9.png">
@candida-d mentioned translating text so I'm tending towards options with limited text.

**Comment by candida-d** [comment]
- I like the new versions! 
-  App > Wallet  > Keys > Passphrase is clear.
- In Recovery Phrase diagram: "Each pair is generated using the same recovery phrase" - what about "regenerated"? Reinforces the idea of recovering keys that already existed. 
- Recovery Phrase diagram has 2 "Recovery Phrase 1"s. There are a couple of other grammar/language tweaks I'd make to the file but I think it's early for them. 
- When it comes to the transactions ones, I don't understand what 'network config' is expressing.

**Comment by ValentinTrinque** [comment]
That's way better to me. Excellent job !
